package qianchuan

// DataTopic 数据主题
type DataTopic string

const (
	// ECP_BASIC_DATA 千川平台广告基础数据
	ECP_BASIC_DATA DataTopic = "ECP_BASIC_DATA"
	// SITE_PROMOTION_POST_DATA_LIVE  全域推广-素材-直播间画面
	SITE_PROMOTION_POST_DATA_LIVE DataTopic = "SITE_PROMOTION_POST_DATA_LIVE"
	// SITE_PROMOTION_POST_DATA_VIDEO  全域推广-素材-视频
	SITE_PROMOTION_POST_DATA_VIDEO DataTopic = "SITE_PROMOTION_POST_DATA_VIDEO"
	// SITE_PROMOTION_POST_DATA_OTHER  全域推广-素材-其他创意
	SITE_PROMOTION_POST_DATA_OTHER DataTopic = "SITE_PROMOTION_POST_DATA_OTHER"
	// SITE_PROMOTION_POST_DATA_TITLE  全域推广-素材-标题
	SITE_PROMOTION_POST_DATA_TITLE DataTopic = "SITE_PROMOTION_POST_DATA_TITLE"
	// SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE 商品全域推广-素材-图片
	SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE DataTopic = "SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE"
	// SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO 商品全域推广-素材-视频
	SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO DataTopic = "SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO"
	// SITE_PROMOTION_PRODUCT_POST_DATA_OTHER  商品全域推广-素材-其他创意
	SITE_PROMOTION_PRODUCT_POST_DATA_OTHER DataTopic = "SITE_PROMOTION_PRODUCT_POST_DATA_OTHER"
	// SITE_PROMOTION_PRODUCT_POST_DATA_TITLE  商品全域推广-素材-标题
	SITE_PROMOTION_PRODUCT_POST_DATA_TITLE DataTopic = "SITE_PROMOTION_PRODUCT_POST_DATA_TITLE"
)
