package liveroom

// Metrics 指标字段
type Metrics struct {
	// StdFormSubmitCntTd 表单提交数
	StdFormSubmitCntTd int64 `json:"std_form_submit_cnt_td,omitempty"`
	// StdAppFirstPaymentCntTD 首次付费数
	StdAppFirstPaymentCntTd int64 `json:"std_app_first_payment_cnt_td,omitempty"`
	// AllLiveWatchCntTd 整体观看数
	AllLiveWatchCntTd int64 `json:"all_live_watch_cnt_td,omitempty"`
	// StdLiveComponentClickCntTd 组件点击数
	StdLiveComponentClickCntTd int64 `json:"std_live_component_click_cnt_td,omitempty"`
	// AllLiveSingleWatchOver1mCntTd 整体超一分钟观看数
	AllLiveSingleWatchOver1mCntTd int64 `json:"all_live_single_watch_over_1m_cnt_td,omitempty"`
	// StdAdCostAmountTd 消耗
	StdAdCostAmountTd float64 `json:"std_ad_cost_amount_td,omitempty"`
	// StdLiveWatchCntTd 直播间观看数
	StdLiveWatchCntTd int64 `json:"std_live_watch_cnt_td,omitempty"`
	// StdAppDownloadStartCntTd 安卓应用下载开始
	StdAppDownloadStartCntTd int64 `json:"std_app_download_start_cnt_td,omitempty"`
	// AllLiveWatchUcntTd 整体直播间观看人数
	AllLiveWatchUcntTd int64 `json:"all_live_watch_ucnt_td,omitempty"`
	// AllLiveEnterRoomUrateTd 整体直播间进入率
	AllLiveEnterRoomUrateTd float64 `json:"all_live_enter_room_urate_td,omitempty"`
	// AllAvgLivePcuTd 整体平均同时在线人数
	AllAvgLivePcuTd int64 `json:"all_avg_live_pcu_td,omitempty"`
	// AllLiveMax1minPcuTd 整体最高同时在线人数
	AllLiveMax1minPcuTd int64 `json:"all_live_max_1min_pcu_td,omitempty"`
	// AllAvgLiveWatchDurationSecondsTd 整体观众平均停留时长
	AllAvgLiveWatchDurationSecondsTd int64 `json:"all_avg_live_watch_duration_seconds_td,omitempty"`
	// AllFansLiveWatchUcntTd 整体粉丝观看人数
	AllFansLiveWatchUcntTd int64 `json:"all_fans_live_watch_ucnt_td,omitempty"`
	// AllFansLiveWatchUrateTd 整体看播粉丝占比
	AllFansLiveWatchUrateTd int64 `json:"all_fans_live_watch_urate_td,omitempty"`
	// AllLiveFollowCntTd 整体关注数
	AllLiveFollowCntTd int64 `json:"all_live_follow_cnt_td,omitempty"`
	// AllLiveFansAvgWatchDurationSecondsTd 整体粉丝人均观看时长
	AllLiveFansAvgWatchDurationSecondsTd int64 `json:"all_live_fans_avg_watch_duration_seconds_td,omitempty"`
	// AllLiveDislikeUcntTd 整体不喜欢人数
	AllLiveDislikeUcntTd int64 `json:"all_live_dislike_ucnt_td,omitempty"`
	// AllLiveDislikeCntTd 整体不喜欢次数
	AllLiveDislikeCntTd int64 `json:"all_live_dislike_cnt_td,omitempty"`
	// AllLiveShareCntTd 整体分享数
	AllLiveShareCntTd int64 `json:"all_live_share_cnt_td,omitempty"`
	// AllLiveShareUcntTd 整体分享人数
	AllLiveShareUcntTd int64 `json:"all_live_share_ucnt_td,omitempty"`
	// AllLiveCommentCntTd 整体评论数
	AllLiveCommentCntTd int64 `json:"all_live_comment_cnt_td,omitempty"`
	// AllLiveCommentUcntTd 整体评论人数
	AllLiveCommentUcntTd int64 `json:"all_live_comment_ucnt_td,omitempty"`
	// AllLiveCommentUrateTd 整体评论率
	AllLiveCommentUrateTd float64 `json:"all_live_comment_urate_td,omitempty"`
	// AllLiveSendGiftCntTd 整体打赏次数
	AllLiveSendGiftCntTd int64 `json:"all_live_send_gift_cnt_td,omitempty"`
	// AllLiveGiftAmountTd 整体礼物总金额
	AllLiveGiftAmountTd float64 `json:"all_live_gift_amount_td,omitempty"`
	// StdAdShowCntTd 展示数
	StdAdShowCntTd int64 `json:"std_ad_show_cnt_td,omitempty"`
	// StdAdClickCntTd 点击数
	StdAdClickCntTd int64 `json:"std_ad_click_cnt_td,omitempty"`
	// StdLiveComponentClickRateTd 组件点击率
	StdLiveComponentClickRateTd float64 `json:"std_live_component_click_rate_td,omitempty"`
	// StdAdConvertCntTd 转化数
	StdAdConvertCntTd int64 `json:"std_ad_convert_cnt_td,omitempty"`
	// StdAdCvrTd 转化率
	StdAdCvrTd float64 `json:"std_ad_cvr_td,omitempty"`
	// StdAdCpmTd 平均千次展示费用
	StdAdCpmTd float64 `json:"std_ad_cpm_td,omitempty"`
	// StdLiveWatchUcntTd 直播间观看人数
	StdLiveWatchUcntTd int64 `json:"std_live_watch_ucnt_td,omitempty"`
	// StdLiveFollowCntTd 直播间关注数
	StdLiveFollowCntTd int64 `json:"std_live_follow_cnt_td,omitempty"`
	// StdLiveFansClubJoinCntTd 直播间加入粉丝团数
	StdLiveFansClubJoinCntTd int64 `json:"std_live_fans_club_join_cnt_td,omitempty"`
	// StdLiveDislikeCntTd 不喜欢次数
	StdLiveDislikeCntTd int64 `json:"std_live_dislike_cnt_td,omitempty"`
	// StdLiveShareCntTd 直播间分享数
	StdLiveShareCntTd int64 `json:"std_live_share_cnt_td,omitempty"`
	// StdLiveShareUcntTd 分享人数
	StdLiveShareUcntTd int64 `json:"std_live_share_ucnt_td,omitempty"`
	// StdLiveCommentCntTd 直播间评论数
	StdLiveCommentCntTd int64 `json:"std_live_comment_cnt_td,omitempty"`
	// StdLiveCommentUcntTd 评论人数
	StdLiveCommentUcntTd int64 `json:"std_live_comment_ucnt_td,omitempty"`
	// StdLiveCommentUrateTd 评论率
	StdLiveCommentUrateTd float64 `json:"std_live_comment_urate_td,omitempty"`
	// StdLiveSendGiftCntTd 直播间打赏次数
	StdLiveSendGiftCntTd int64 `json:"std_live_send_gift_cnt_td,omitempty"`
	// StdLiveGiftAmountTd 直播间礼物总金额
	StdLiveGiftAmountTd float64 `json:"std_live_gift_amount_td,omitempty"`
	// StdLiveComponentShowCntTd 组件展示数
	StdLiveComponentShowCntTd int64 `json:"std_live_component_show_cnt_td,omitempty"`
	// StdCustomerEffectiveCntTd 有效获客
	StdCustomerEffectiveCntTd int64 `json:"std_customer_effective_cnt_td,omitempty"`
	// StdConsultEffectiveCntTd 有效咨询
	StdConsultEffectiveCntTd int64 `json:"std_consult_effective_cnt_td,omitempty"`
	// StdWorkWechatAddedCntTd 添加企业微信数
	StdWorkWechatAddedCntTd int64 `json:"std_work_wechat_added_cnt_td,omitempty"`
	// StdPremiumPaymentCntTd 保险支付数
	StdPremiumPaymentCntTd int64 `json:"std_premium_payment_cnt_td,omitempty"`
	// StdAppDownloadFinishCntTd 安卓下载完成数
	StdAppDownloadFinishCntTd int64 `json:"std_app_download_finish_cnt_td,omitempty"`
	// StdAppActiveCntTd 安卓应用激活
	StdAppActiveCntTd int64 `json:"std_app_active_cnt_td,omitempty"`
	// StdAppAttributionNextDayOpenCntTd 次留数
	StdAppAttributionNextDayOpenCntTd int64 `json:"std_app_attribution_next_day_open_cnt_td,omitempty"`
	// StdAttributionNextDayOpenRateTd 次留率
	StdAppAttributionNextDayOpenRateTd float64 `json:"std_app_attribution_next_day_open_rate_td,omitempty"`
	// StdAppInstallFinishCntTd 安卓应用安装完成
	StdAppInstallFinishCntTd int64 `json:"std_app_install_finish_cnt_td,omitempty"`
	// AllLiveEnterRoomRateTd 整体直播间外层点击率
	AllLiveEnterRoomRateTd float64 `json:"all_live_enter_room_rate_td,omitempty"`
	// AllLiveSingleWatchOver1mRateTd 整体超一分钟观看率
	AllLiveSingleWatchOverr1mRateTd float64 `json:"all_live_single_watch_over_1m_rate_td,omitempty"`
	// AllLiveLikeCntTd 整体点赞数
	AllLiveLikeCntTd int64 `json:"all_live_like_cnt_td,omitempty"`
	// StdAdCtrTd 点击率
	StdAdCtrTd float64 `json:"std_ad_ctr_td,omitempty"`
	// StdLiveWatchUrateTd 直播间进入率
	StdLiveWatchUrateTd float64 `json:"std_live_watch_urate_td,omitempty"`
	// StdInWechatPayCntTd 微信内付费
	StdWechatPayCntTd int64 `json:"std_wechat_pay_cnt_td,omitempty"`
	// StdAvgLiveWatchDurationSecondsTd 观众平均停留时长
	StdAvgLiveWatchDurationSecondsTd int64 `json:"std_avg_live_watch_duration_seconds_td,omitempty"`
	// StdLiveFollowUrateTd 关注率
	StdLiveFollowUrateTd float64 `json:"std_live_follow_urate_td,omitempty"`
	// StdAppActiveRegisterCntTd 注册数
	StdAppActiveRegisterCntTd int64 `json:"std_app_active_register_cnt_td,omitempty"`
	// StdAppGamePayCntTd 付费次数
	StdAppGamePayCntTd int64 `json:"std_app_game_pay_cnt_td,omitempty"`
	// AllLiveDislikeUrateTd 整体不喜欢率
	AllLiveDislikeUrateTd float64 `json:"all_Live_dislike_urate_td,omitempty"`
	// AllLiveShareUrateTd 整体分享率
	AllLiveShareUrateTd float64 `json:"all_live_share_urate_td,omitempty"`
	// AllLiveLikeUrateTd 整体点赞率
	AllLiveLikeUrateTd float64 `json:"all_live_like_urate_td,omitempty"`
	// AllLiveFollowUrateTd 整体关注率
	AllLiveFollowUrateTd float64 `json:"all_live_follow_urate_td,omitempty"`
	// AllFansLiveCommentCntTd 整体粉丝评论次数
	AllFansLiveCommentCntTd int64 `json:"all_fans_live_comment_cnt_td,omitempty"`
	// StdLiveSingleWatchOver1mCntTd 直播间超一分钟停留次数
	StdLiveSingleWatchOver1mCntTd int64 `json:"std_live_single_watch_over_1m_cnt_td,omitempty"`
	// StdLiveShareUrateTd 分享率
	StdLiveShareUrateTd float64 `json:"std_live_share_urate_td,omitempty"`
	// AllLiveFansClubJoinCntTd 整体加入粉丝团数
	AllLiveFansClubJoinCntTd int64 `json:"all_live_fans_club_join_cnt_td,omitempty"`
}
