package local

// ClueReasonCode 线索事件状态扩展标签
type ClueReasonCode string

const (
	// ClueReasonCode_CALL_THREE_TIMES_NO_RESPONSE 拨打3次以上未接通
	ClueReasonCode_CALL_THREE_TIMES_NO_RESPONSE ClueReasonCode = "CALL_THREE_TIMES_NO_RESPONSE"
	// ClueReasonCode_INVALID_NUMBER 空号/停机/关机
	ClueReasonCode_INVALID_NUMBER ClueReasonCode = "INVALID_NUMBER"
	// ClueReasonCode_NO_AD_RESPONSE 反馈未在广告留资
	ClueReasonCode_NO_AD_RESPONSE ClueReasonCode = "NO_AD_RESPONSE"
	// ClueReasonCode_CONNECTED_NO_INTENTION 接通但无意向
	ClueReasonCode_CONNECTED_NO_INTENTION ClueReasonCode = "CONNECTED_NO_INTENTION"
	// ClueReasonCode_OFFENSIVE_LANGUAGE 黑脏词
	ClueReasonCode_OFFENSIVE_LANGUAGE ClueReasonCode = "OFFENSIVE_LANGUAGE"
	// ClueReasonCode_OTHER 其它
	ClueReasonCode_OTHER ClueReasonCode = "OTHER"
	// ClueReasonCode_HOME_COLLABORATION_WITH_PEERS (家居)同行合作
	ClueReasonCode_HOME_COLLABORATION_WITH_PEERS ClueReasonCode = "HOME_COLLABORATION_WITH_PEERS"
	// ClueReasonCode_HOME_NO_SHOW_FOR_MEASUREMENT_VISIT (家居)爽约上门量房
	ClueReasonCode_HOME_NO_SHOW_FOR_MEASUREMENT_VISIT ClueReasonCode = "HOME_NO_SHOW_FOR_MEASUREMENT_VISIT"
	// ClueReasonCode_HOME_RENOVATION_TYPE_NOT_ACCEPTABLE (家居)装修类型不可承接
	ClueReasonCode_HOME_RENOVATION_TYPE_NOT_ACCEPTABLE ClueReasonCode = "HOME_RENOVATION_TYPE_NOT_ACCEPTABLE"
	// ClueReasonCode_HOME_MISMATCH_DIFFERENT_LOCATIONS (家居)需求不匹配-需求与供给异地，原MISMATCH_DIFFERENT_LOCATIONS枚举逐步下线中
	ClueReasonCode_HOME_MISMATCH_DIFFERENT_LOCATIONS ClueReasonCode = "HOME_MISMATCH_DIFFERENT_LOCATIONS"
	// ClueReasonCode_HOME_MISMATCH_LOW_BUDGET (家居)需求不匹配-消费力差（指代预算少/面积小），原MISMATCH_LOW_BUDGET枚举逐步下线中
	ClueReasonCode_HOME_MISMATCH_LOW_BUDGET ClueReasonCode = "HOME_MISMATCH_LOW_BUDGET"
	// ClueReasonCode_EDU_MISMATCH_CLASS_TIME (教育)需求不匹配-上课时间不匹配
	ClueReasonCode_EDU_MISMATCH_CLASS_TIME ClueReasonCode = "EDU_MISMATCH_CLASS_TIME"
	// ClueReasonCode_EDU_MISMATCH_COURSE (教育)需求不匹配-课程不匹配
	ClueReasonCode_EDU_MISMATCH_COURSE ClueReasonCode = "EDU_MISMATCH_COURSE"
	// ClueReasonCode_EDU_MISMATCH_DIFFERENT_LOCATIONS (教育)需求不匹配-需求与供给异地
	ClueReasonCode_EDU_MISMATCH_DIFFERENT_LOCATIONS ClueReasonCode = "EDU_MISMATCH_DIFFERENT_LOCATIONS"
	// ClueReasonCode_EDU_UNABLE_TO_ATTEND_IN_PERSON (教育)无法线下参加
	ClueReasonCode_EDU_UNABLE_TO_ATTEND_IN_PERSON ClueReasonCode = "EDU_UNABLE_TO_ATTEND_IN_PERSON"
	// ClueReasonCode_HOME_MEASUREMENT_COMPLETED [家居]已量房
	ClueReasonCode_HOME_MEASUREMENT_COMPLETED ClueReasonCode = "HOME_MEASUREMENT_COMPLETED"
	// ClueReasonCode_HOME_ORDER_DISPATCHED [家居]已派单
	ClueReasonCode_HOME_ORDER_DISPATCHED ClueReasonCode = "HOME_ORDER_DISPATCHED"
	// ClueReasonCode_HOME_APPOINTMENT_SCHEDULED [家居]已约时间
	ClueReasonCode_HOME_APPOINTMENT_SCHEDULED ClueReasonCode = "HOME_APPOINTMENT_SCHEDULED"
	// ClueReasonCode_HOME_CAN_ADD_WECHAT [家居]可加微
	ClueReasonCode_HOME_CAN_ADD_WECHAT ClueReasonCode = "HOME_CAN_ADD_WECHAT"
	// ClueReasonCode_HOME_CONNECTED_WITH_INTERESTED_PARTY [家居]接通有意向
	ClueReasonCode_HOME_CONNECTED_WITH_INTERESTED_PARTY ClueReasonCode = "HOME_CONNECTED_WITH_INTERESTED_PARTY"
	//   ClueReasonCode_EDU_FIRST_CLASS_ATTENDED [教育]首次到课
	ClueReasonCode_EDU_FIRST_CLASS_ATTENDED ClueReasonCode = "EDU_FIRST_CLASS_ATTENDED"
	// ClueReasonCode_EDU_INTERESTED [教育]有意向
	ClueReasonCode_EDU_INTERESTED ClueReasonCode = "EDU_INTERESTED"
	//   ClueReasonCode_HOME_CONTRACT_SIGNED [家居]已签约
	ClueReasonCode_HOME_CONTRACT_SIGNED ClueReasonCode = "HOME_CONTRACT_SIGNED"
	// ClueReasonCode_HOME_SERVICE_DELIVERY_COMPLETED [家居]已完成服务交付
	ClueReasonCode_HOME_SERVICE_DELIVERY_COMPLETED ClueReasonCode = "HOME_SERVICE_DELIVERY_COMPLETED"
)
