package enum

// AccountRole 授权账号角色
type AccountRole string

const (
	// ADVERTISER 广告主
	ADVERTISER AccountRole = "ADVERTISER"
	// CUSTOMER_ADMIN 管家-管理员
	CUSTOMER_ADMIN AccountRole = "CUSTOMER_ADMIN"
	// AGENT 代理商
	AGENT AccountRole = "AGENT"
	// CHILD_AGENT 二级代理商
	CHILD_AGENT AccountRole = "CHILD_AGENT"
	// CUSTOMER_OPERATOR 管家-操作者
	CUSTOMER_OPERATOR AccountRole = "CUSTOMER_OPERATOR"
	// PLATFORM_ROLE_QIANCHUAN_AGENT 代理商账户
	PLATFORM_ROLE_QIANCHUAN_AGENT AccountRole = "PLATFORM_ROLE_QIANCHUAN_AGENT"
	// PLATFORM_ROLE_SHOP_ACCOUNT 店铺账户
	PLATFORM_ROLE_SHOP_ACCOUNT AccountRole = "PLATFORM_ROLE_SHOP_ACCOUNT"
	// PLATFORM_ROLE_STAR 星图客户
	PLATFORM_ROLE_STAR AccountRole = "PLATFORM_ROLE_STAR"
	// PLATFORM_ROLE_STAR_AGENT 星图代理商
	PLATFORM_ROLE_STAR_AGENT AccountRole = "PLATFORM_ROLE_STAR_AGENT"
	// PLATFORM_ROLE_LOCAL_AGENT 本地推代理商
	PLATFORM_ROLE_LOCAL_AGENT AccountRole = "PLATFORM_ROLE_LOCAL_AGENT"
)
