package enum

// AdConvertType 转化类型
type AdConvertType string

const (
	// AD_CONVERT_TYPE_EFFECTIVE_PLAY 有效播放
	AD_CONVERT_TYPE_EFFECTIVE_PLAY AdConvertType = "AD_CONVERT_TYPE_EFFECTIVE_PLAY"
	// AD_CONVERT_TYPE_CLICK_NUM 点击量
	AD_CONVERT_TYPE_CLICK_NUM AdConvertType = "AD_CONVERT_TYPE_CLICK_NUM"
	// AD_CONVERT_TYPE_SHOW_OFF_NUM 展示量
	AD_CONVERT_TYPE_SHOW_OFF_NUM AdConvertType = "AD_CONVERT_TYPE_SHOW_OFF_NUM"
	// AD_CONVERT_TYPE_PHONE 电话拨打
	AD_CONVERT_TYPE_PHONE AdConvertType = "AD_CONVERT_TYPE_PHONE"
	// AD_CONVERT_TYPE_FORM 表单提交
	AD_CONVERT_TYPE_FORM AdConvertType = "AD_CONVERT_TYPE_FORM"
	// AD_CONVERT_TYPE_MAP_SEARCH 地图搜索
	AD_CONVERT_TYPE_MAP_SEARCH AdConvertType = "AD_CONVERT_TYPE_MAP_SEARCH"
	// AD_CONVERT_TYPE_DOWNLOAD_FINISH 下载完成
	AD_CONVERT_TYPE_DOWNLOAD_FINISH AdConvertType = "AD_CONVERT_TYPE_DOWNLOAD_FINISH"
	// AD_CONVERT_TYPE_BUTTON 按钮跳转
	AD_CONVERT_TYPE_BUTTON AdConvertType = "AD_CONVERT_TYPE_BUTTON"
	// AD_CONVERT_TYPE_XPATH xpath类型转换
	AD_CONVERT_TYPE_XPATH AdConvertType = "AD_CONVERT_TYPE_XPATH"
	// AD_CONVERT_TYPE_VIEW 关键页面浏览
	AD_CONVERT_TYPE_VIEW AdConvertType = "AD_CONVERT_TYPE_VIEW"
	// AD_CONVERT_TYPE_ACTIVE 激活
	AD_CONVERT_TYPE_ACTIVE AdConvertType = "AD_CONVERT_TYPE_ACTIVE"
	// AD_CONVERT_TYPE_DOWNLOAD_START 下载按钮download_start
	AD_CONVERT_TYPE_DOWNLOAD_START AdConvertType = "AD_CONVERT_TYPE_DOWNLOAD_START"
	// AD_CONVERT_TYPE_QQ qq咨询
	AD_CONVERT_TYPE_QQ AdConvertType = "AD_CONVERT_TYPE_QQ"
	// AD_CONVERT_TYPE_LOTTERY 抽奖
	AD_CONVERT_TYPE_LOTTERY AdConvertType = "AD_CONVERT_TYPE_LOTTERY"
	// AD_CONVERT_TYPE_VOTE 投票
	AD_CONVERT_TYPE_VOTE AdConvertType = "AD_CONVERT_TYPE_VOTE"
	// AD_CONVERT_TYPE_ACTIVE_REGISTER 激活且注册
	AD_CONVERT_TYPE_ACTIVE_REGISTER AdConvertType = "AD_CONVERT_TYPE_ACTIVE_REGISTER"
	// AD_CONVERT_TYPE_PAY 激活且付费
	AD_CONVERT_TYPE_PAY AdConvertType = "AD_CONVERT_TYPE_PAY"
	// AD_CONVERT_TYPE_INSTALL_FINISH 安装完成
	AD_CONVERT_TYPE_INSTALL_FINISH AdConvertType = "AD_CONVERT_TYPE_INSTALL_FINISH"
	// AD_CONVERT_TYPE_PHONE_CONFIRM 智能电话-确认拨打
	AD_CONVERT_TYPE_PHONE_CONFIRM AdConvertType = "AD_CONVERT_TYPE_PHONE_CONFIRM"
	// AD_CONVERT_TYPE_PHONE_CONNECT 智能电话-确认接通
	AD_CONVERT_TYPE_PHONE_CONNECT AdConvertType = "AD_CONVERT_TYPE_PHONE_CONNECT"
	// AD_CONVERT_TYPE_PHONE_EFFECTIVE 智能电话-有效接通
	AD_CONVERT_TYPE_PHONE_EFFECTIVE AdConvertType = "AD_CONVERT_TYPE_PHONE_EFFECTIVE"
	// AD_CONVERT_TYPE_CONSULT_EFFECTIVE 有效咨询
	AD_CONVERT_TYPE_CONSULT_EFFECTIVE AdConvertType = "AD_CONVERT_TYPE_CONSULT_EFFECTIVE"
	// AD_CONVERT_TYPE_APP_ORDER app内下单（电商）
	AD_CONVERT_TYPE_APP_ORDER AdConvertType = "AD_CONVERT_TYPE_APP_ORDER"
	// AD_CONVERT_TYPE_APP_UV app内访问
	AD_CONVERT_TYPE_APP_UV AdConvertType = "AD_CONVERT_TYPE_APP_UV"
	// AD_CONVERT_TYPE_APP_CART app内添加购物车（电商）
	AD_CONVERT_TYPE_APP_CART AdConvertType = "AD_CONVERT_TYPE_APP_CART"
	// AD_CONVERT_TYPE_APP_PAY app内付费
	AD_CONVERT_TYPE_APP_PAY AdConvertType = "AD_CONVERT_TYPE_APP_PAY"
	// AD_CONVERT_TYPE_SALES_LEAD 销售线索
	AD_CONVERT_TYPE_SALES_LEAD AdConvertType = "AD_CONVERT_TYPE_SALES_LEAD"
	// AD_CONVERT_TYPE_GAME_ADDICTION 关键行为（原深度转化）
	AD_CONVERT_TYPE_GAME_ADDICTION AdConvertType = "AD_CONVERT_TYPE_GAME_ADDICTION"
	// AD_CONVERT_TYPE_CUSTOMER_EFFECTIVE 有效获客
	AD_CONVERT_TYPE_CUSTOMER_EFFECTIVE AdConvertType = "AD_CONVERT_TYPE_CUSTOMER_EFFECTIVE"
	// AD_CONVERT_TYPE_EFFECTIVE_COPY 关键页面到达&有效内容复制
	AD_CONVERT_TYPE_EFFECTIVE_COPY AdConvertType = "AD_CONVERT_TYPE_EFFECTIVE_COPY"
	// AD_CONVERT_TYPE_COUPON 卡券领取
	AD_CONVERT_TYPE_COUPON AdConvertType = "AD_CONVERT_TYPE_COUPON"
	// AD_CONVERT_TYPE_APP_DETAIL_UV app内详情页到站uv
	AD_CONVERT_TYPE_APP_DETAIL_UV AdConvertType = "AD_CONVERT_TYPE_APP_DETAIL_UV"
	// AD_CONVERT_TYPE_RSS 账号关注
	AD_CONVERT_TYPE_RSS AdConvertType = "AD_CONVERT_TYPE_RSS"
	// AD_CONVERT_TYPE_FORM_CONNECT 表单提交-已接通
	AD_CONVERT_TYPE_FORM_CONNECT AdConvertType = "AD_CONVERT_TYPE_FORM_CONNECT"
	// AD_CONVERT_TYPE_FORM_ANSWER 有效沟通
	AD_CONVERT_TYPE_FORM_ANSWER AdConvertType = "AD_CONVERT_TYPE_FORM_ANSWER"
	// AD_CONVERT_TYPE_DIALBACK 提交回呼电话
	AD_CONVERT_TYPE_DIALBACK AdConvertType = "AD_CONVERT_TYPE_DIALBACK"
	// AD_CONVERT_TYPE_DIALBACK_CONFIRM 回呼电话-确认拨打
	AD_CONVERT_TYPE_DIALBACK_CONFIRM AdConvertType = "AD_CONVERT_TYPE_DIALBACK_CONFIRM"
	// AD_CONVERT_TYPE_DIALBACK_CONNECT 回呼电话-确认接通
	AD_CONVERT_TYPE_DIALBACK_CONNECT AdConvertType = "AD_CONVERT_TYPE_DIALBACK_CONNECT"
	// AD_CONVERT_TYPE_FORM_DEEP 分层表单
	AD_CONVERT_TYPE_FORM_DEEP AdConvertType = "AD_CONVERT_TYPE_FORM_DEEP"
	// AD_CONVERT_TYPE_UPDATE_LEVEL 激活且升级
	AD_CONVERT_TYPE_UPDATE_LEVEL AdConvertType = "AD_CONVERT_TYPE_UPDATE_LEVEL"
	// AD_CONVERT_TYPE_CREATE_GAMEROLE 激活且创建角色
	AD_CONVERT_TYPE_CREATE_GAMEROLE AdConvertType = "AD_CONVERT_TYPE_CREATE_GAMEROLE"
	// AD_CONVERT_TYPE_NEXT_DAY_OPEN 激活且次留
	AD_CONVERT_TYPE_NEXT_DAY_OPEN AdConvertType = "AD_CONVERT_TYPE_NEXT_DAY_OPEN"
	// AD_CONVERT_TYPE_INVALID_CLUE 无效线索
	AD_CONVERT_TYPE_INVALID_CLUE AdConvertType = "AD_CONVERT_TYPE_INVALID_CLUE"
	// AD_CONVERT_TYPE_INTENTION_CLUE 有意向客户
	AD_CONVERT_TYPE_INTENTION_CLUE AdConvertType = "AD_CONVERT_TYPE_INTENTION_CLUE"
	// AD_CONVERT_TYPE_HIGH_VALUE_CLUE 高价值客户
	AD_CONVERT_TYPE_HIGH_VALUE_CLUE AdConvertType = "AD_CONVERT_TYPE_HIGH_VALUE_CLUE"
	// AD_CONVERT_TYPE_PAID_CLUE 已成单
	AD_CONVERT_TYPE_PAID_CLUE AdConvertType = "AD_CONVERT_TYPE_PAID_CLUE"
	// AD_CONVERT_TYPE_NATIVE_ACTION 原生互动
	AD_CONVERT_TYPE_NATIVE_ACTION AdConvertType = "AD_CONVERT_TYPE_NATIVE_ACTION"
	// AD_CONVERT_TYPE_LIKE_ACTION 视频点赞
	AD_CONVERT_TYPE_LIKE_ACTION AdConvertType = "AD_CONVERT_TYPE_LIKE_ACTION"
	// AD_CONVERT_TYPE_FOLLOW_ACTION 账户关注
	AD_CONVERT_TYPE_FOLLOW_ACTION AdConvertType = "AD_CONVERT_TYPE_FOLLOW_ACTION"
	// AD_CONVERT_TYPE_COMMENT_ACTION 视频评论
	AD_CONVERT_TYPE_COMMENT_ACTION AdConvertType = "AD_CONVERT_TYPE_COMMENT_ACTION"
	// AD_CONVERT_TYPE_LOCATION_ACTION POI点击
	AD_CONVERT_TYPE_LOCATION_ACTION AdConvertType = "AD_CONVERT_TYPE_LOCATION_ACTION"
	// AD_CONVERT_TYPE_SHOPPING_ACTION 购物车点击
	AD_CONVERT_TYPE_SHOPPING_ACTION AdConvertType = "AD_CONVERT_TYPE_SHOPPING_ACTION"
	// AD_CONVERT_TYPE_REDIRECT_TO_SHOP 调起店铺
	AD_CONVERT_TYPE_REDIRECT_TO_SHOP AdConvertType = "AD_CONVERT_TYPE_REDIRECT_TO_SHOP"
	// AD_CONVERT_TYPE_LINK_ACTION link点击
	AD_CONVERT_TYPE_LINK_ACTION AdConvertType = "AD_CONVERT_TYPE_LINK_ACTION"
	// AD_CONVERT_TYPE_DEEP_PURCHASE 多次付费
	AD_CONVERT_TYPE_DEEP_PURCHASE AdConvertType = "AD_CONVERT_TYPE_DEEP_PURCHASE"
	// AD_CONVERT_TYPE_SUCCESSORDER_ACTION 小店转化
	AD_CONVERT_TYPE_SUCCESSORDER_ACTION AdConvertType = "AD_CONVERT_TYPE_SUCCESSORDER_ACTION"
	// AD_CONVERT_TYPE_POI_COLLECT poi地址点击
	AD_CONVERT_TYPE_POI_COLLECT AdConvertType = "AD_CONVERT_TYPE_POI_COLLECT"
	// AD_CONVERT_TYPE_POI_ADDRESS_CLICK poi收藏
	AD_CONVERT_TYPE_POI_ADDRESS_CLICK AdConvertType = "AD_CONVERT_TYPE_POI_ADDRESS_CLICK"
	// AD_CONVERT_TYPE_RESERVATION poi预定
	AD_CONVERT_TYPE_RESERVATION AdConvertType = "AD_CONVERT_TYPE_RESERVATION"
	// AD_CONVERT_TYPE_MESSAGE_ACTION 私信消息
	AD_CONVERT_TYPE_MESSAGE_ACTION AdConvertType = "AD_CONVERT_TYPE_MESSAGE_ACTION"
	// AD_CONVERT_TYPE_SHARE_ACTION 分享
	AD_CONVERT_TYPE_SHARE_ACTION AdConvertType = "AD_CONVERT_TYPE_SHARE_ACTION"
	// AD_CONVERT_TYPE_CLICK_LANDING_PAGE 访问推广详情页
	AD_CONVERT_TYPE_CLICK_LANDING_PAGE AdConvertType = "AD_CONVERT_TYPE_CLICK_LANDING_PAGE"
	// AD_CONVERT_TYPE_CLICK_SHOPWINDOW 访问主页商品橱窗
	AD_CONVERT_TYPE_CLICK_SHOPWINDOW AdConvertType = "AD_CONVERT_TYPE_CLICK_SHOPWINDOW"
	// AD_CONVERT_TYPE_CLICK_DOWNLOAD 访问主页下载应用
	AD_CONVERT_TYPE_CLICK_DOWNLOAD AdConvertType = "AD_CONVERT_TYPE_CLICK_DOWNLOAD"
	// AD_CONVERT_TYPE_CLICK_CALL_DY 点击主页内电话拨打
	AD_CONVERT_TYPE_CLICK_CALL_DY AdConvertType = "AD_CONVERT_TYPE_CLICK_CALL_DY"
	// AD_CONVERT_TYPE_CLICK_WEBSITE 访问主页官网
	AD_CONVERT_TYPE_CLICK_WEBSITE AdConvertType = "AD_CONVERT_TYPE_CLICK_WEBSITE"
	// AD_CONVERT_PAGE_VIEW 访问目标页面
	AD_CONVERT_PAGE_VIEW AdConvertType = "AD_CONVERT_PAGE_VIEW"
	// AD_CONVERT_TYPE_MESSAGE 短信
	AD_CONVERT_TYPE_MESSAGE AdConvertType = "AD_CONVERT_TYPE_MESSAGE"
	// AD_CONVERT_TYPE_REDIRECT 页面跳转
	AD_CONVERT_TYPE_REDIRECT AdConvertType = "AD_CONVERT_TYPE_REDIRECT"
	// AD_CONVERT_TYPE_SHOPPING 商品购买
	AD_CONVERT_TYPE_SHOPPING AdConvertType = "AD_CONVERT_TYPE_SHOPPING"
	// AD_CONVERT_TYPE_CONSULT 在线咨询
	AD_CONVERT_TYPE_CONSULT AdConvertType = "AD_CONVERT_TYPE_CONSULT"
	// AD_CONVERT_TYPE_WECHAT 微信
	AD_CONVERT_TYPE_WECHAT AdConvertType = "AD_CONVERT_TYPE_WECHAT"
	// AD_CONVERT_TYPE_OTHER 其他
	AD_CONVERT_TYPE_OTHER AdConvertType = "AD_CONVERT_TYPE_OTHER"
	// AD_CONVERT_TYPE_MULTIPLE 多转化事件
	AD_CONVERT_TYPE_MULTIPLE AdConvertType = "AD_CONVERT_TYPE_MULTIPLE"
	// AD_CONVERT_TYPE_POI_MULTIPLE POI门店多转化目标
	AD_CONVERT_TYPE_POI_MULTIPLE AdConvertType = "AD_CONVERT_TYPE_POI_MULTIPLE"
	// AD_CONVERT_TYPE_INTERACTION 互动
	AD_CONVERT_TYPE_INTERACTION AdConvertType = "AD_CONVERT_TYPE_INTERACTION"
	// AD_CONVERT_TYPE_LOAN_COMPLETION 互联网金融-完件
	AD_CONVERT_TYPE_LOAN_COMPLETION AdConvertType = "AD_CONVERT_TYPE_LOAN_COMPLETION"
	// AD_CONVERT_TYPE_PRE_LOAN_CREDIT 互联网金融-预授信
	AD_CONVERT_TYPE_PRE_LOAN_CREDIT AdConvertType = "AD_CONVERT_TYPE_PRE_LOAN_CREDIT"
	// AD_CONVERT_TYPE_LOAN_CREDIT 互联网金融-授信
	AD_CONVERT_TYPE_LOAN_CREDIT AdConvertType = "AD_CONVERT_TYPE_LOAN_CREDIT"
	// AD_CONVERT_TYPE_IDCARD_INFORMATION 身份证信息填写完成
	AD_CONVERT_TYPE_IDCARD_INFORMATION AdConvertType = "AD_CONVERT_TYPE_IDCARD_INFORMATION"
	// AD_CONVERT_TYPE_BANKCARD_INFORMATION 银行卡信息填写完成
	AD_CONVERT_TYPE_BANKCARD_INFORMATION AdConvertType = "AD_CONVERT_TYPE_BANKCARD_INFORMATION"
	// AD_CONVERT_TYPE_PERSONAL_INFORMATION 补充个人信息填写完成
	AD_CONVERT_TYPE_PERSONAL_INFORMATION AdConvertType = "AD_CONVERT_TYPE_PERSONAL_INFORMATION"
	// AD_CONVERT_TYPE_CERTIFICATION_INFORMATION 用户活体认证信息上传完成
	AD_CONVERT_TYPE_CERTIFICATION_INFORMATION AdConvertType = "AD_CONVERT_TYPE_CERTIFICATION_INFORMATION"
	// AD_CONVERT_TYPE_LT_ROI 广告变现ROI
	AD_CONVERT_TYPE_LT_ROI AdConvertType = "AD_CONVERT_TYPE_LT_ROI"
	// AD_CONVERT_TYPE_LIVE_HOMEPAGE 直播导流
	AD_CONVERT_TYPE_LIVE_HOMEPAGE AdConvertType = "AD_CONVERT_TYPE_LIVE_HOMEPAGE"
	// AD_CONVERT_TYPE_REDIRECT_TO_STORE 店铺导流
	AD_CONVERT_TYPE_REDIRECT_TO_STORE AdConvertType = "AD_CONVERT_TYPE_REDIRECT_TO_STORE"
	// AD_CONVERT_TYPE_FEED_LIVE_HOMEPAGE 火山feed进入直播页
	AD_CONVERT_TYPE_FEED_LIVE_HOMEPAGE AdConvertType = "AD_CONVERT_TYPE_FEED_LIVE_HOMEPAGE"
	// AD_CONVERT_TYPE_AUTHORIZATION 授权（电商）
	AD_CONVERT_TYPE_AUTHORIZATION AdConvertType = "AD_CONVERT_TYPE_AUTHORIZATION"
	// AD_CONVERT_TYPE_COMMODITY_CLICK 快上电商推广目的
	AD_CONVERT_TYPE_COMMODITY_CLICK AdConvertType = "AD_CONVERT_TYPE_COMMODITY_CLICK"
	// AD_CONVERT_TYPE_CONSULT_CLUE 留咨咨询
	AD_CONVERT_TYPE_CONSULT_CLUE AdConvertType = "AD_CONVERT_TYPE_CONSULT_CLUE"
	// AD_CONVERT_TYPE_BOOST 自然助推
	AD_CONVERT_TYPE_BOOST AdConvertType = "AD_CONVERT_TYPE_BOOST"
	// AD_CONVERT_TYPE_STAY_TIME 店铺停留
	AD_CONVERT_TYPE_STAY_TIME AdConvertType = "AD_CONVERT_TYPE_STAY_TIME"
	// AD_CONVERT_TYPE_PURCHASE_OF_GOODS 商品签收
	AD_CONVERT_TYPE_PURCHASE_OF_GOODS AdConvertType = "AD_CONVERT_TYPE_PURCHASE_OF_GOODS"
	// AD_CONVERT_TYPE_PURCHASE_ROI 付费ROI
	AD_CONVERT_TYPE_PURCHASE_ROI AdConvertType = "AD_CONVERT_TYPE_PURCHASE_ROI"
	// AD_CONVERT_TYPE_LIVE_NATIVE_ACITON 直播间原生互动
	AD_CONVERT_TYPE_LIVE_NATIVE_ACITON AdConvertType = "AD_CONVERT_TYPE_LIVE_NATIVE_ACITON"
	// AD_CONVERT_TYPE_LIVE_FOLLOW_ACITON 直播间关注
	AD_CONVERT_TYPE_LIVE_FOLLOW_ACITON AdConvertType = "AD_CONVERT_TYPE_LIVE_FOLLOW_ACITON"
	// AD_CONVERT_TYPE_LIVE_COMMENT_ACTION 直播间评论
	AD_CONVERT_TYPE_LIVE_COMMENT_ACTION AdConvertType = "AD_CONVERT_TYPE_LIVE_COMMENT_ACTION"
	// AD_CONVERT_TYPE_LIVE_GIFT_ACTION 直播间内打赏
	AD_CONVERT_TYPE_LIVE_GIFT_ACTION AdConvertType = "AD_CONVERT_TYPE_LIVE_GIFT_ACTION"
	// AD_CONVERT_TYPE_LIVE_SLIDECART_CLICK_ACTION 直播间查看购物车
	AD_CONVERT_TYPE_LIVE_SLIDECART_CLICK_ACTION AdConvertType = "AD_CONVERT_TYPE_LIVE_SLIDECART_CLICK_ACTION"
	// AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION 直播间查看商品
	AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION AdConvertType = "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION"
	// AD_CONVERT_TYPE_LIVE_ENTER_ACTION 直播间观看
	AD_CONVERT_TYPE_LIVE_ENTER_ACTION AdConvertType = "AD_CONVERT_TYPE_LIVE_ENTER_ACTION"
	// AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION 直播间成单
	AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION AdConvertType = "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION"
	// AD_CONVERT_TYPE_NOTIFY_DOWNLOAD 预约下载
	AD_CONVERT_TYPE_NOTIFY_DOWNLOAD AdConvertType = "AD_CONVERT_TYPE_NOTIFY_DOWNLOAD"
	// AD_CONVERT_TYPE_PREMIUM_PAYMENT 保险支付
	AD_CONVERT_TYPE_PREMIUM_PAYMENT AdConvertType = "AD_CONVERT_TYPE_PREMIUM_PAYMENT"
	// AD_CONVERT_TYPE_MESSAGE_CLICK 私信点击
	AD_CONVERT_TYPE_MESSAGE_CLICK AdConvertType = "AD_CONVERT_TYPE_MESSAGE_CLICK"
	// AD_CONVERT_TYPE_UG_ROI 内广roi
	AD_CONVERT_TYPE_UG_ROI AdConvertType = "AD_CONVERT_TYPE_UG_ROI"
	// AD_CONVERT_TYPE_ENTER_HOMEPAGE 进入个人主页
	AD_CONVERT_TYPE_ENTER_HOMEPAGE AdConvertType = "AD_CONVERT_TYPE_ENTER_HOMEPAGE"
	// AD_CONVERT_TYPE_SHOPPING_CART 商品购物车点击
	AD_CONVERT_TYPE_SHOPPING_CART AdConvertType = "AD_CONVERT_TYPE_SHOPPING_CART"
	// AD_CONVERT_TYPE_WECHAT_REGISTER 微信内注册
	AD_CONVERT_TYPE_WECHAT_REGISTER AdConvertType = "AD_CONVERT_TYPE_WECHAT_REGISTER"
	// AD_CONVERT_TYPE_WECHAT_PAY 微信内付费
	AD_CONVERT_TYPE_WECHAT_PAY AdConvertType = "AD_CONVERT_TYPE_WECHAT_PAY"
	// AD_CONVERT_TYPE_MESSAGE_INTERACTION 沟通互动
	AD_CONVERT_TYPE_MESSAGE_INTERACTION AdConvertType = "AD_CONVERT_TYPE_MESSAGE_INTERACTION"
	// AD_CONVERT_TYPE_LIVE_STAY_TIME 直播间停留
	AD_CONVERT_TYPE_LIVE_STAY_TIME AdConvertType = "AD_CONVERT_TYPE_LIVE_STAY_TIME"
	// AD_CONVERT_TYPE_NEW_FOLLOW_ACTION 粉丝增长
	AD_CONVERT_TYPE_NEW_FOLLOW_ACTION AdConvertType = "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION"
	// AD_CONVERT_TYPE_APPLET_CLICK 小程序互动
	AD_CONVERT_TYPE_APPLET_CLICK AdConvertType = "AD_CONVERT_TYPE_APPLET_CLICK"
	// AD_CONVERT_TYPE_MESSAGE_SERVICE 私信服务
	AD_CONVERT_TYPE_MESSAGE_SERVICE AdConvertType = "AD_CONVERT_TYPE_MESSAGE_SERVICE"
	// AD_CONVERT_TYPE_MESSAGE_CLUE 私信留资
	AD_CONVERT_TYPE_MESSAGE_CLUE AdConvertType = "AD_CONVERT_TYPE_MESSAGE_CLUE"
	// AD_CONVERT_TYPE_LIVE_FANS_ACTION 直播间加入粉丝团
	AD_CONVERT_TYPE_LIVE_FANS_ACTION AdConvertType = "AD_CONVERT_TYPE_LIVE_FANS_ACTION"
	// AD_CONVERT_TYPE_CLUE_CONFIRM 回访_信息确认
	AD_CONVERT_TYPE_CLUE_CONFIRM AdConvertType = "AD_CONVERT_TYPE_CLUE_CONFIRM"
	// AD_CONVERT_TYPE_CLUE_INTERFLOW 回访_加为好友
	AD_CONVERT_TYPE_CLUE_INTERFLOW AdConvertType = "AD_CONVERT_TYPE_CLUE_INTERFLOW"
	// AD_CONVERT_TYPE_CLUE_HIGH_INTENTION 回访_高潜成交
	AD_CONVERT_TYPE_CLUE_HIGH_INTENTION AdConvertType = "AD_CONVERT_TYPE_CLUE_HIGH_INTENTION"
	// AD_CONVERT_TYPE_SUBMIT_CERTIFICATION 提交认证
	AD_CONVERT_TYPE_SUBMIT_CERTIFICATION AdConvertType = "AD_CONVERT_TYPE_SUBMIT_CERTIFICATION"
	// AD_CONVERT_TYPE_FIRST_RENTAL_ORDER 首次发单
	AD_CONVERT_TYPE_FIRST_RENTAL_ORDER AdConvertType = "AD_CONVERT_TYPE_FIRST_RENTAL_ORDER"
	// AD_CONVERT_TYPE_LIVE_COMPONENT_CLICK 组件点击
	AD_CONVERT_TYPE_LIVE_COMPONENT_CLICK AdConvertType = "AD_CONVERT_TYPE_LIVE_COMPONENT_CLICK"
	// AD_CONVERT_TYPE_LIVE_BUSINESS_FITTING 直播间组件点击
	AD_CONVERT_TYPE_LIVE_BUSINESS_FITTING AdConvertType = "AD_CONVERT_TYPE_LIVE_BUSINESS_FITTING"
	// AD_CONVERT_TYPE_CLUE_PAY_SUCCEED 支付_存在意向
	AD_CONVERT_TYPE_CLUE_PAY_SUCCEED AdConvertType = "AD_CONVERT_TYPE_CLUE_PAY_SUCCEED"
	// AD_CONVERT_TYPE_OTO_STAY_TIME 团单浏览
	AD_CONVERT_TYPE_OTO_STAY_TIME AdConvertType = "AD_CONVERT_TYPE_OTO_STAY_TIME"
	// AD_CONVERT_TYPE_OTO_PAY 团购支付
	AD_CONVERT_TYPE_OTO_PAY AdConvertType = "AD_CONVERT_TYPE_OTO_PAY"
	// AD_CONVERT_TYPE_PREMIUM_ROI 保费ROI
	AD_CONVERT_TYPE_PREMIUM_ROI AdConvertType = "AD_CONVERT_TYPE_PREMIUM_ROI"
	// AD_CONVERT_TYPE_MESSAGE_ORDER_SUCCESS 私信成单
	AD_CONVERT_TYPE_MESSAGE_ORDER_SUCCESS AdConvertType = "AD_CONVERT_TYPE_MESSAGE_ORDER_SUCCESS"
	// AD_CONVERT_TYPE_MESSAGE_JOIN_GROUP 私信用户入群
	AD_CONVERT_TYPE_MESSAGE_JOIN_GROUP AdConvertType = "AD_CONVERT_TYPE_MESSAGE_JOIN_GROUP"
	// AD_CONVERT_TYPE_LIVE_JOIN_GROUP 粉丝入群
	AD_CONVERT_TYPE_LIVE_JOIN_GROUP AdConvertType = "AD_CONVERT_TYPE_LIVE_JOIN_GROUP"
	// AD_CONVERT_TYPE_LIVE_APPOINTMENT 预约直播
	AD_CONVERT_TYPE_LIVE_APPOINTMENT AdConvertType = "AD_CONVERT_TYPE_LIVE_APPOINTMENT"
	// AD_CONVERT_TYPE_FOLLOW_LIVE_ENTER 粉丝访问直播
	AD_CONVERT_TYPE_FOLLOW_LIVE_ENTER AdConvertType = "AD_CONVERT_TYPE_FOLLOW_LIVE_ENTER"
	// AD_CONVERT_TYPE_FOLLOW_CLICK_PRODUCT 关注并加购
	AD_CONVERT_TYPE_FOLLOW_CLICK_PRODUCT AdConvertType = "AD_CONVERT_TYPE_FOLLOW_CLICK_PRODUCT"
	// AD_CONVERT_TYPE_FOLLOW_VIDEO_PLAY_FINISH 粉丝观看
	AD_CONVERT_TYPE_FOLLOW_VIDEO_PLAY_FINISH AdConvertType = "AD_CONVERT_TYPE_FOLLOW_VIDEO_PLAY_FINISH"
	// AD_CONVERT_TYPE_GAMESTATION_DOWNLOAD_DOUPLUS 游戏站下载 - DOU +
	AD_CONVERT_TYPE_GAMESTATION_DOWNLOAD_DOUPLUS AdConvertType = "AD_CONVERT_TYPE_GAMESTATION_DOWNLOAD_DOUPLUS"
	// AD_CONVERT_TYPE_QC_FOLLOW_ACTION 提升粉丝
	AD_CONVERT_TYPE_QC_FOLLOW_ACTION AdConvertType = "AD_CONVERT_TYPE_QC_FOLLOW_ACTION"
	// AD_CONVERT_TYPE_QC_MUST_BUY 内容种草
	AD_CONVERT_TYPE_QC_MUST_BUY AdConvertType = "AD_CONVERT_TYPE_QC_MUST_BUY"
	// AD_CONVERT_TYPE_NOTIFY_FORM 预约表单
	AD_CONVERT_TYPE_NOTIFY_FORM AdConvertType = "AD_CONVERT_TYPE_NOTIFY_FORM"
	// AD_CONVERT_TYPE_IPU_QUALIFY 激活首日广告展示达标
	AD_CONVERT_TYPE_IPU_QUALIFY AdConvertType = "AD_CONVERT_TYPE_IPU_QUALIFY"
	// AD_CONVERT_TYPE_ANCHOR_CLICK 直播支付ROI
	AD_CONVERT_TYPE_ANCHOR_CLICK AdConvertType = "AD_CONVERT_TYPE_ANCHOR_CLICK"
	// AD_CONVERT_TYPE_WECHAT_WECOM_ADD 添加企业微信
	AD_CONVERT_TYPE_WECHAT_WECOM_ADD AdConvertType = "AD_CONVERT_TYPE_WECHAT_WECOM_ADD"
	// AD_CONVERT_TYPE_WECHAT_FIRST_MSG 微信_用户首次消息
	AD_CONVERT_TYPE_WECHAT_FIRST_MSG AdConvertType = "AD_CONVERT_TYPE_WECHAT_FIRST_MSG"
	// AD_CONVERT_TYPE_RETENTION_DAYS 留存天数
	AD_CONVERT_TYPE_RETENTION_DAYS AdConvertType = "AD_CONVERT_TYPE_RETENTION_DAYS"
	// AD_CONVERT_TYPE_INTELLIGENT_SERVICE_OPEN 微信_用户首次消息
	AD_CONVERT_TYPE_INTELLIGENT_SERVICE_OPEN AdConvertType = "AD_CONVERT_TYPE_INTELLIGENT_SERVICE_OPEN"
	// AD_CONVERT_ADD_TO_CART 引流电商种草
	AD_CONVERT_ADD_TO_CART AdConvertType = "AD_CONVERT_ADD_TO_CART"
)
