package enum

// AdvancedCreativeType 附加创意类型
type AdvancedCreativeType string

const (
	// ATTACHED_CREATIVE_NONE 无
	ATTACHED_CREATIVE_NONE AdvancedCreativeType = "ATTACHED_CREATIVE_NONE"
	// ATTACHED_CREATIVE_PHONE 电话拨打
	ATTACHED_CREATIVE_PHONE AdvancedCreativeType = "ATTACHED_CREATIVE_PHONE"
	// ATTACHED_CREATIVE_FORM 表单收集
	ATTACHED_CREATIVE_FORM AdvancedCreativeType = "ATTACHED_CREATIVE_FORM"
	// ATTACHED_CREATIVE_COMMERCE_CARD 电商（即落地页）卡片
	ATTACHED_CREATIVE_COMMERCE_CARD AdvancedCreativeType = "ATTACHED_CREATIVE_COMMERCE_CARD"
	// ATTACHED_CREATIVE_DOWNLOAD_CARD 商品下载卡片
	ATTACHED_CREATIVE_DOWNLOAD_CARD AdvancedCreativeType = "ATTACHED_CREATIVE_DOWNLOAD_CARD"
	// ATTACHED_CREATIVE_CONSULTANT 在线咨询
	ATTACHED_CREATIVE_CONSULTANT AdvancedCreativeType = "ATTACHED_CREATIVE_CONSULTANT"
	// ATTACHED_CREATIVE_COUPON 卡券
	ATTACHED_CREATIVE_COUPON AdvancedCreativeType = "ATTACHED_CREATIVE_COUPON"
	// ATTACHED_CREATIVE_CARD 图片磁贴
	ATTACHED_CREATIVE_CARD AdvancedCreativeType = "ATTACHED_CREATIVE_CARD"
	// ATTACHED_CREATIVE_INTERACT 选择磁贴
	ATTACHED_CREATIVE_INTERACT AdvancedCreativeType = "ATTACHED_CREATIVE_INTERACT"
	// ATTACHED_CREATIVE_SMART_PHONE 智能电话
	ATTACHED_CREATIVE_SMART_PHONE AdvancedCreativeType = "ATTACHED_CREATIVE_SMART_PHONE"
	// ATTACHED_CREATIVE_VOTE_INTERACT 投票磁贴
	ATTACHED_CREATIVE_VOTE_INTERACT AdvancedCreativeType = "ATTACHED_CREATIVE_VOTE_INTERACT"
	// ATTACHED_CREATIVE_GAME_PACKAGE 游戏礼包
	ATTACHED_CREATIVE_GAME_PACKAGE AdvancedCreativeType = "ATTACHED_CREATIVE_GAME_PACKAGE"
	// ATTACHED_CREATIVE_COUPON_INTERACT 优惠券磁贴
	ATTACHED_CREATIVE_COUPON_INTERACT AdvancedCreativeType = "ATTACHED_CREATIVE_COUPON_INTERACT"
	// ATTACHED_CREATIVE_GAME_FORM 游戏表单收集
	ATTACHED_CREATIVE_GAME_FORM AdvancedCreativeType = "ATTACHED_CREATIVE_GAME_FORM"
	// ATTACHED_CREATIVE_GAME_SUBSCRIBE 游戏预约按钮
	ATTACHED_CREATIVE_GAME_SUBSCRIBE AdvancedCreativeType = "ATTACHED_CREATIVE_GAME_SUBSCRIBE"
)
