package enum

// AsyncTaskStatus 异步任务状态
type AsyncTaskStatus string

const (
	// ASYNC_TASK_STATUS_CREATED 任务已创建
	ASYNC_TASK_STATUS_CREATED AsyncTaskStatus = "ASYNC_TASK_STATUS_CREATED"
	// ASYNC_TASK_STATUS_EXECUTING 任务执行中
	ASYNC_TASK_STATUS_EXECUTING AsyncTaskStatus = "ASYNC_TASK_STATUS_EXECUTING"
	// ASYNC_TASK_STATUS_EXECUTING_STAGE2 任务处理中
	ASYNC_TASK_STATUS_EXECUTING_STAGE2 AsyncTaskStatus = "ASYNC_TASK_STATUS_EXECUTING_STAGE2"
	// ASYNC_TASK_STATUS_COMPLETED 任务执行完成
	ASYNC_TASK_STATUS_COMPLETED AsyncTaskStatus = "ASYNC_TASK_STATUS_COMPLETED"
	// ASYNC_TASK_STATUS_EXPIRED 任务过期
	ASYNC_TASK_STATUS_EXPIRED AsyncTaskStatus = "ASYNC_TASK_STATUS_EXPIRED"
)
