package enum

type AudienceStatIDType string

const (
	AUDIENCE_STAT_ID_TYPE_ADVERTISER AudienceStatIDType = "AUDIENCE_STAT_ID_TYPE_ADVERTISER"
	AUDIENCE_STAT_ID_TYPE_CAMPAIGN   AudienceStatIDType = "AUDIENCE_STAT_ID_TYPE_CAMPAIGN"
	AUDIENCE_STAT_ID_TYPE_AD         AudienceStatIDType = "AUDIENCE_STAT_ID_TYPE_AD"
	AUDIENCE_STAT_ID_TYPE_CREATIVE   AudienceStatIDType = "AUDIENCE_STAT_ID_TYPE_CREATIVE"
)
