package enum

// AutoGenerateConfigTemplateType 模板类型
type AutoGenerateConfigTemplateType string

const (
	// AutoGenerateConfigTemplateType_HORIZONTAL_TO_VERTICAL_DYNAMIC_BACK_VIDEO 横转竖动效背景视频
	AutoGenerateConfigTemplateType_HORIZONTAL_TO_VERTICAL_DYNAMIC_BACK_VIDEO AutoGenerateConfigTemplateType = "HORIZONTAL_TO_VERTICAL_DYNAMIC_BACK_VIDEO"
	// AutoGenerateConfigTemplateType_VERTICAL_TO_HORIZONTAL_DYNAMIC_BACK_VIDEO 竖转横动效背景视频
	AutoGenerateConfigTemplateType_VERTICAL_TO_HORIZONTAL_DYNAMIC_BACK_VIDEO AutoGenerateConfigTemplateType = "VERTICAL_TO_HORIZONTAL_DYNAMIC_BACK_VIDEO"
	// AutoGenerateConfigTemplateType_VERTICAL_TO_HORIZONTAL_STATIC_BACK_VIDEO 竖转横静态背景视频
	AutoGenerateConfigTemplateType_VERTICAL_TO_HORIZONTAL_STATIC_BACK_VIDEO AutoGenerateConfigTemplateType = "VERTICAL_TO_HORIZONTAL_STATIC_BACK_VIDEO"
)
