package enum

// CreativeWordStatus 动态词包状态
type CreativeWordStatus string

const (
	// CREATIVE_WORD_STATUS_APPROVE 审核通过
	CREATIVE_WORD_STATUS_APPROVE CreativeWordStatus = "CREATIVE_WORD_STATUS_APPROVE"
	// CREATIVE_WORD_STATUS_REJECT 审核失败
	CREATIVE_WORD_STATUS_REJECT CreativeWordStatus = "CREATIVE_WORD_STATUS_REJECT"
	// CREATIVE_WORD_STATUS_AUDIT 新建审核中
	CREATIVE_WORD_STATUS_AUDIT CreativeWordStatus = "CREATIVE_WORD_STATUS_AUDIT"
	// CREATIVE_WORD_STATUS_REAUDIT 修改审核中
	CREATIVE_WORD_STATUS_REAUDIT CreativeWordStatus = "CREATIVE_WORD_STATUS_REAUDIT"
)
