package enum

// DmpSource 人群包来源
type DmpSource = string

const (
	// CUSTOM_AUDIENCE_TYPE_UPLOAD 上传
	CUSTOM_AUDIENCE_TYPE_UPLOAD DmpSource = "CUSTOM_AUDIENCE_TYPE_UPLOAD"
	// CUSTOM_AUDIENCE_TYPE_EXTEND 扩展
	CUSTOM_AUDIENCE_TYPE_EXTEND DmpSource = "CUSTOM_AUDIENCE_TYPE_EXTEND"
	// CUSTOM_AUDIENCE_TYPE_OPERATE 运算
	CUSTOM_AUDIENCE_TYPE_OPERATE DmpSource = "CUSTOM_AUDIENCE_TYPE_OPERATE"
	// CUSTOM_AUDIENCE_TYPE_RULE 规则
	CUSTOM_AUDIENCE_TYPE_RULE DmpSource = "CUSTOM_AUDIENCE_TYPE_RULE"
	// CUSTOM_AUDIENCE_TYPE_DATA_SOURCE 文件数据源上传
	CUSTOM_AUDIENCE_TYPE_DATA_SOURCE DmpSource = "CUSTOM_AUDIENCE_TYPE_DATA_SOURCE"
	// CUSTOM_AUDIENCE_TYPE_THIRD_PARTY 第三方数据规则
	CUSTOM_AUDIENCE_TYPE_THIRD_PARTY DmpSource = "CUSTOM_AUDIENCE_TYPE_THIRD_PARTY"
	// CUSTOM_AUDIENCE_TYPE_BRAND 品牌DMP规则包
	CUSTOM_AUDIENCE_TYPE_BRAND DmpSource = "CUSTOM_AUDIENCE_TYPE_BRAND"
	// CUSTOM_AUDIENCE_TYPE_FRIEND 好友扩展
	CUSTOM_AUDIENCE_TYPE_FRIEND DmpSource = "CUSTOM_AUDIENCE_TYPE_FRIEND"
	// CUSTOM_AUDIENCE_TYPE_THEME 运营主题
	CUSTOM_AUDIENCE_TYPE_THEME DmpSource = "CUSTOM_AUDIENCE_TYPE_THEME"
	// CUSTOM_AUDIENCE_TYPE_FINANCE 金融数据
	CUSTOM_AUDIENCE_TYPE_FINANCE DmpSource = "CUSTOM_AUDIENCE_TYPE_FINANCE"
	// CUSTOM_AUDIENCE_TYPE_PACK_RULE pack_rule运算
	CUSTOM_AUDIENCE_TYPE_PACK_RULE DmpSource = "CUSTOM_AUDIENCE_TYPE_PACK_RULE"
	// CUSTOM_AUDIENCE_TYPE_ONE_KEY 一键拓展
	CUSTOM_AUDIENCE_TYPE_ONE_KEY DmpSource = "CUSTOM_AUDIENCE_TYPE_ONE_KEY"
	// CUSTOM_AUDIENCE_TYPE_DOU_PLUS 抖+粉丝合并包
	CUSTOM_AUDIENCE_TYPE_DOU_PLUS DmpSource = "CUSTOM_AUDIENCE_TYPE_DOU_PLUS"
)
