package enum

type DmpSource = int

const (
	// CUSTOM_AUDIENCE_TYPE_UPLOAD 上传
	CUSTOM_AUDIENCE_TYPE_UPLOAD DmpSource = 0
	// CUSTOM_AUDIENCE_TYPE_EXTEND 扩展
	CUSTOM_AUDIENCE_TYPE_EXTEND DmpSource = 1
	// CUSTOM_AUDIENCE_TYPE_OPERATE 运算
	CUSTOM_AUDIENCE_TYPE_OPERATE DmpSource = 2
	// CUSTOM_AUDIENCE_TYPE_RULE 规则
	CUSTOM_AUDIENCE_TYPE_RULE DmpSource = 3
	// CUSTOM_AUDIENCE_TYPE_DATA_SOURCE 文件数据源上传
	CUSTOM_AUDIENCE_TYPE_DATA_SOURCE DmpSource = 4
	// CUSTOM_AUDIENCE_TYPE_THIRD_PARTY 第三方数据规则
	CUSTOM_AUDIENCE_TYPE_THIRD_PARTY DmpSource = 5
	// CUSTOM_AUDIENCE_TYPE_BRAND 品牌DMP规则包
	CUSTOM_AUDIENCE_TYPE_BRAND DmpSource = 6
	// CUSTOM_AUDIENCE_TYPE_FRIEND 好友扩展
	CUSTOM_AUDIENCE_TYPE_FRIEND DmpSource = 7
	// CUSTOM_AUDIENCE_TYPE_THEME 运营主题
	CUSTOM_AUDIENCE_TYPE_THEME DmpSource = 8
	// CUSTOM_AUDIENCE_TYPE_FINANCE 金融数据
	CUSTOM_AUDIENCE_TYPE_FINANCE DmpSource = 9
	// CUSTOM_AUDIENCE_TYPE_PACK_RULE pack_rule运算
	CUSTOM_AUDIENCE_TYPE_PACK_RULE DmpSource = 10
	// CUSTOM_AUDIENCE_TYPE_ONE_KEY 一键拓展
	CUSTOM_AUDIENCE_TYPE_ONE_KEY DmpSource = 11
	// CUSTOM_AUDIENCE_TYPE_DOU_PLUS 抖+粉丝合并包
	CUSTOM_AUDIENCE_TYPE_DOU_PLUS DmpSource = 12
)
