package enum

// Holiday 节假日
type Holiday string

const (
	// NEW_YEAR 元旦
	NEW_YEAR Holiday = "NEW_YEAR"
	// SPRING_FESTIVAL 春节
	SPRING_FESTIVAL Holiday = "SPRING_FESTIVAL"
	// VALENTINES_DAY 情人节
	VALENTINES_DAY Holiday = "VALENTINES_DAY"
	// LABOUR_DAY 五一
	LABOUR_DAY Holiday = "LABOUR_DAY"
	// DRAGON_BOAT_FESTIVAL 端午
	DRAGON_BOAT_FESTIVAL Holiday = "DRAGON_BOAT_FESTIVAL"
	// CHINESE_VALENTINES_DAY 七夕
	CHINESE_VALENTINES_DAY Holiday = "CHINESE_VALENTINES_DAY"
	// MOON_FESTIVAL 中秋
	MOON_FESTIVAL Holiday = "MOON_FESTIVAL"
	// NATIONAL_DAY 国庆
	NATIONAL_DAY Holiday = "NATIONAL_DAY"
	// CHRISTMAS 圣诞节
	CHRISTMAS Holiday = "CHRISTMAS"
	// SHOPPING_DAY_618 618
	SHOPPING_DAY_618 Holiday = "SHOPPING_DAY_618"
	// SHOPPING_DAY_1111 双11
	SHOPPING_DAY_1111 Holiday = "SHOPPING_DAY_1111"
)
