package enum

// LandingGroupStatus 落地页组状态
type LandingGroupStatus string

const (
	// LANDING_GROUP_STATUS_AVAILABLE 可用
	LANDING_GROUP_STATUS_AVAILABLE LandingGroupStatus = "LANDING_GROUP_STATUS_AVAILABLE"
	// LANDING_GROUP_STATUS_UNAVAILABLE 不可用
	LANDING_GROUP_STATUS_UNAVAILABLE LandingGroupStatus = "LANDING_GROUP_STATUS_UNAVAILABLE"
)
