package enum

// MaterialStatus 素材审核状态
type MaterialStatus string

const (

	// MATERIAL_STATUS_OK 投放中
	MATERIAL_STATUS_OK MaterialStatus = "MATERIAL_STATUS_OK"
	// MATERIAL_STATUS_DELETE 已删除
	MATERIAL_STATUS_DELETE MaterialStatus = "MATERIAL_STATUS_DELETE"
	// MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET 项目超出预算
	MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET MaterialStatus = "MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET"
	// MATERIAL_STATUS_PROJECT_PREOFFLINE_BUDGET 项目接近预算
	MATERIAL_STATUS_PROJECT_PREOFFLINE_BUDGET MaterialStatus = "MATERIAL_STATUS_PROJECT_PREOFFLINE_BUDGET"
	// MATERIAL_STATUS_TIME_NO_REACH 未到达投放时间
	MATERIAL_STATUS_TIME_NO_REACH MaterialStatus = "MATERIAL_STATUS_TIME_NO_REACH"
	// MATERIAL_STATUS_TIME_DONE 已完成
	MATERIAL_STATUS_TIME_DONE MaterialStatus = "MATERIAL_STATUS_TIME_DONE"
	// MATERIAL_STATUS_NO_SCHEDULE 不在投放时段
	MATERIAL_STATUS_NO_SCHEDULE MaterialStatus = "MATERIAL_STATUS_NO_SCHEDULE"
	// MATERIAL_STATUS_AUDIT 新建审核中
	MATERIAL_STATUS_AUDIT MaterialStatus = "MATERIAL_STATUS_AUDIT"
	// MATERIAL_STATUS_REAUDIT 修改审核中
	MATERIAL_STATUS_REAUDIT MaterialStatus = "MATERIAL_STATUS_REAUDIT"
	// MATERIAL_STATUS_OFFLINE_AUDIT 审核不通过
	MATERIAL_STATUS_OFFLINE_AUDIT MaterialStatus = "MATERIAL_STATUS_OFFLINE_AUDIT"
	// MATERIAL_STATUS_OFFLINE_BUDGET 广告超出预算
	MATERIAL_STATUS_OFFLINE_BUDGET MaterialStatus = "MATERIAL_STATUS_OFFLINE_BUDGET"
	// MATERIAL_STATUS_OFFLINE_BALANCE 账户余额不足
	MATERIAL_STATUS_OFFLINE_BALANCE MaterialStatus = "MATERIAL_STATUS_OFFLINE_BALANCE"
	// MATERIAL_STATUS_PREOFFLINE_BUGDET 广告接近预算
	MATERIAL_STATUS_PREOFFLINE_BUGDET MaterialStatus = "MATERIAL_STATUS_PREOFFLINE_BUGDET"
	// MATERIAL_STATUS_PROJECT_DISABLE 已被项目暂停
	MATERIAL_STATUS_PROJECT_DISABLE MaterialStatus = "MATERIAL_STATUS_PROJECT_DISABLE"
	// MATERIAL_STATUS_DISABLE 已暂停
	MATERIAL_STATUS_DISABLE MaterialStatus = "MATERIAL_STATUS_DISABLE"
	// MATERIAL_STATUS_PROMOTION_DISABLE 已被广告暂停
	MATERIAL_STATUS_PROMOTION_DISABLE MaterialStatus = "MATERIAL_STATUS_PROMOTION_DISABLE"
	// MATERIAL_STATUS_MATERIAL_DELETE 已删除
	MATERIAL_STATUS_MATERIAL_DELETE MaterialStatus = "MATERIAL_STATUS_MATERIAL_DELETE"
)
