package enum

// QualificationType 广告主资质类型
type QualificationType string

const (
	// QUALIFICATION_DESCRIPTION 推广内容
	QUALIFICATION_DESCRIPTION QualificationType = "QUALIFICATION_DESCRIPTION"
	// QUALIFICATION_LICENSE 营业执照
	QUALIFICATION_LICENSE QualificationType = "QUALIFICATION_LICENSE"
	// QUALIFICATION_ACCOUNT 开户资质
	QUALIFICATION_ACCOUNT QualificationType = "QUALIFICATION_ACCOUNT"
	// QUALIFICATION_AD 投放资质
	QUALIFICATION_AD QualificationType = "QUALIFICATION_AD"
)
