package enum

// StatInventoryType 投放位置
// (INVENTORY_BEAUTY/INVENTORY_PIPIXIA/INVENTORY_AUTOMOBILE/INVENTORY_STUDY/INVENTORY_FACE_U枚举值仅在报表接口可用)
// 信息流（INVENTORY_FEED）与详情页（INVENTORY_TEXT_LINK）合并为头条系（依然使用INVENTORY_FEED字段，名称更改为头条系）
type StatInventoryType string

const (
	// INVENTORY_FEED 头条信息流（广告投放）
	INVENTORY_FEED StatInventoryType = "INVENTORY_FEED"
	// INVENTORY_TEXT_LINK 头条文章详情页（已废弃）
	INVENTORY_TEXT_LINK StatInventoryType = "INVENTORY_TEXT_LINK"
	// INVENTORY_VIDEO_FEED 西瓜信息流（广告投放）
	INVENTORY_VIDEO_FEED StatInventoryType = "INVENTORY_VIDEO_FEED"
	// INVENTORY_HOTSOON_FEED 火山信息流（广告投放）
	INVENTORY_HOTSOON_FEED StatInventoryType = "INVENTORY_HOTSOON_FEED"
	// INVENTORY_AWEME_FEED 抖音信息流（广告投放）
	INVENTORY_AWEME_FEED StatInventoryType = "INVENTORY_AWEME_FEED"
	// INVENTORY_UNION_SLOT 穿山甲（广告投放）
	INVENTORY_UNION_SLOT StatInventoryType = "INVENTORY_UNION_SLOT"
	// UNION_BOUTIQUE_GAME 穿山甲精选休闲游戏（广告投放）
	UNION_BOUTIQUE_GAME StatInventoryType = "UNION_BOUTIQUE_GAME"
	// INVENTORY_UNION_SPLASH_SLOT 穿山甲开屏广告（广告投放）
	INVENTORY_UNION_SPLASH_SLOT StatInventoryType = "INVENTORY_UNION_SPLASH_SLOT"
	// INVENTORY_AWEME_SEARCH 搜索广告——抖音位（广告投放）
	INVENTORY_AWEME_SEARCH StatInventoryType = "INVENTORY_AWEME_SEARCH"
	// INVENTORY_SEARCH 搜索广告——头条位（广告投放）
	INVENTORY_SEARCH StatInventoryType = "INVENTORY_SEARCH"
	// INVENTORY_UNIVERSAL 通投智选（广告投放）
	INVENTORY_UNIVERSAL StatInventoryType = "INVENTORY_UNIVERSAL"
	// INVENTORY_BEAUTY 轻颜相机
	INVENTORY_BEAUTY StatInventoryType = "INVENTORY_BEAUTY"
	// INVENTORY_PIPIXIA 皮皮虾
	INVENTORY_PIPIXIA StatInventoryType = "INVENTORY_PIPIXIA"
	// INVENTORY_AUTOMOBILE 懂车帝
	INVENTORY_AUTOMOBILE StatInventoryType = "INVENTORY_AUTOMOBILE"
	// INVENTORY_STUDY 好好学习
	INVENTORY_STUDY StatInventoryType = "INVENTORY_STUDY"
	// INVENTORY_FACE_U faceu
	INVENTORY_FACE_U StatInventoryType = "INVENTORY_FACE_U"
	// INVENTORY_TOMATO_NOVEL 番茄小说
	INVENTORY_TOMATO_NOVEL StatInventoryType = "INVENTORY_TOMATO_NOVEL"
	// INVENTORY_HOMED_AGGREGATE 住小帮
	INVENTORY_HOMED_AGGREGATE StatInventoryType = "INVENTORY_HOMED_AGGREGATE"
)
