// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: github.com/bububa/oceanengine/marketing-api/model/dmp/datasource/dmp.proto

package datasource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdItem_DataType int32

const (
	IdItem_IMEI               IdItem_DataType = 0
	IdItem_IDFA               IdItem_DataType = 1
	IdItem_UID                IdItem_DataType = 2
	IdItem_IMEI_MD5           IdItem_DataType = 4
	IdItem_IDFA_MD5           IdItem_DataType = 5
	IdItem_MOBILE_HASH_SHA256 IdItem_DataType = 6
	IdItem_OAID               IdItem_DataType = 7
	IdItem_OAID_MD5           IdItem_DataType = 8
)

// Enum value maps for IdItem_DataType.
var (
	IdItem_DataType_name = map[int32]string{
		0: "IMEI",
		1: "IDFA",
		2: "UID",
		4: "IMEI_MD5",
		5: "IDFA_MD5",
		6: "MOBILE_HASH_SHA256",
		7: "OAID",
		8: "OAID_MD5",
	}
	IdItem_DataType_value = map[string]int32{
		"IMEI":               0,
		"IDFA":               1,
		"UID":                2,
		"IMEI_MD5":           4,
		"IDFA_MD5":           5,
		"MOBILE_HASH_SHA256": 6,
		"OAID":               7,
		"OAID_MD5":           8,
	}
)

func (x IdItem_DataType) Enum() *IdItem_DataType {
	p := new(IdItem_DataType)
	*p = x
	return p
}

func (x IdItem_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdItem_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_enumTypes[0].Descriptor()
}

func (IdItem_DataType) Type() protoreflect.EnumType {
	return &file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_enumTypes[0]
}

func (x IdItem_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IdItem_DataType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IdItem_DataType(num)
	return nil
}

// Deprecated: Use IdItem_DataType.Descriptor instead.
func (IdItem_DataType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescGZIP(), []int{1, 0}
}

type DmpData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdList []*IdItem `protobuf:"bytes,1,rep,name=idList" json:"idList,omitempty"` // 每行数据包含的idList大小不能超过10000
}

func (x *DmpData) Reset() {
	*x = DmpData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DmpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmpData) ProtoMessage() {}

func (x *DmpData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmpData.ProtoReflect.Descriptor instead.
func (*DmpData) Descriptor() ([]byte, []int) {
	return file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescGZIP(), []int{0}
}

func (x *DmpData) GetIdList() []*IdItem {
	if x != nil {
		return x.IdList
	}
	return nil
}

type IdItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *uint32          `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`                                //若不设置，默认以上传文件的创建时间为此条记录的创建时间
	DataType  *IdItem_DataType `protobuf:"varint,2,req,name=dataType,enum=toutiao.dmp.IdItem_DataType" json:"dataType,omitempty"` //指定此id的类型，如IMEI、IDFA等
	Id        *string          `protobuf:"bytes,3,req,name=id" json:"id,omitempty"`                                               //根据dataType字段的类型，放置对应类型的id的字符串，需要小写
	Tags      []string         `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`                                           //标识此id的业务标签字符串
}

func (x *IdItem) Reset() {
	*x = IdItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdItem) ProtoMessage() {}

func (x *IdItem) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdItem.ProtoReflect.Descriptor instead.
func (*IdItem) Descriptor() ([]byte, []int) {
	return file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescGZIP(), []int{1}
}

func (x *IdItem) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *IdItem) GetDataType() IdItem_DataType {
	if x != nil && x.DataType != nil {
		return *x.DataType
	}
	return IdItem_IMEI
}

func (x *IdItem) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *IdItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto protoreflect.FileDescriptor

var file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDesc = []byte{
	0x0a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x62,
	0x75, 0x62, 0x61, 0x2f, 0x6f, 0x63, 0x65, 0x61, 0x6e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x64, 0x6d, 0x70, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2f, 0x64, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x6f,
	0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x64, 0x6d, 0x70, 0x22, 0x36, 0x0a, 0x07, 0x44, 0x6d, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x64,
	0x6d, 0x70, 0x2e, 0x49, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0xf9, 0x01, 0x0a, 0x06, 0x49, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x38, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x74,
	0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x64, 0x6d, 0x70, 0x2e, 0x49, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x73, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4d, 0x45, 0x49, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x49, 0x44, 0x46, 0x41, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4d, 0x45, 0x49, 0x5f, 0x4d, 0x44, 0x35, 0x10, 0x04, 0x12,
	0x0c, 0x0a, 0x08, 0x49, 0x44, 0x46, 0x41, 0x5f, 0x4d, 0x44, 0x35, 0x10, 0x05, 0x12, 0x16, 0x0a,
	0x12, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x5f, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x53, 0x48, 0x41,
	0x32, 0x35, 0x36, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x41, 0x49, 0x44, 0x10, 0x07, 0x12,
	0x0c, 0x0a, 0x08, 0x4f, 0x41, 0x49, 0x44, 0x5f, 0x4d, 0x44, 0x35, 0x10, 0x08, 0x42, 0x50, 0x42,
	0x0c, 0x44, 0x6d, 0x70, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x40, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x62, 0x75, 0x62, 0x61,
	0x2f, 0x6f, 0x63, 0x65, 0x61, 0x6e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x64, 0x6d, 0x70, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
}

var (
	file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescOnce sync.Once
	file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescData = file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDesc
)

func file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescGZIP() []byte {
	file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescOnce.Do(func() {
		file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescData)
	})
	return file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDescData
}

var file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_goTypes = []interface{}{
	(IdItem_DataType)(0), // 0: toutiao.dmp.IdItem.DataType
	(*DmpData)(nil),      // 1: toutiao.dmp.DmpData
	(*IdItem)(nil),       // 2: toutiao.dmp.IdItem
}
var file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_depIdxs = []int32{
	2, // 0: toutiao.dmp.DmpData.idList:type_name -> toutiao.dmp.IdItem
	0, // 1: toutiao.dmp.IdItem.dataType:type_name -> toutiao.dmp.IdItem.DataType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_init() }
func file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_init() {
	if File_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DmpData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_goTypes,
		DependencyIndexes: file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_depIdxs,
		EnumInfos:         file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_enumTypes,
		MessageInfos:      file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_msgTypes,
	}.Build()
	File_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto = out.File
	file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_rawDesc = nil
	file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_goTypes = nil
	file_github_com_bububa_oceanengine_marketing_api_model_dmp_datasource_dmp_proto_depIdxs = nil
}
